#!/usr/bin/env bash
#
# One-shot setup for release signing.
#
#   1. Has 1Password generate the keystore password
#   2. Generates the release keystore with it
#   3. Stores the keystore file itself in 1Password as a backup
#   4. Loads the four GitHub Actions secrets the release workflow needs
#   5. Prints the certificate fingerprint so you can confirm it later
#
# The password is generated by 1Password and only ever moves through an
# environment variable, so it never appears in argv (visible via ps), in shell
# history, or on stdout.
#
# Losing this keystore means no existing install can ever be updated again --
# every user would have to uninstall and reinstall. Step 3 is not optional.
#
# Run it yourself:  ! ./tools/setup-release-signing.sh
#
set -euo pipefail

REPO="${REPO:-AWare/rotation}"
VAULT="${VAULT:-Private}"
ALIAS="${ALIAS:-rotation}"
KEYSTORE="${KEYSTORE:-$HOME/keys/rotation-release.jks}"
ITEM="${ITEM:-Rotation Android release signing key}"
DNAME="${DNAME:-CN=Rotation, O=AWare, C=GB}"
# ~27 years. An expired certificate strands existing installs just as badly as
# a lost one.
VALIDITY_DAYS=10000

die() { echo "error: $*" >&2; exit 1; }

# --- preflight -------------------------------------------------------------
command -v op >/dev/null || die "1Password CLI not found. Install it (AUR: 1password-cli) and run 'op signin'."
command -v gh >/dev/null || die "GitHub CLI not found."

KEYTOOL="$(command -v keytool || true)"
[ -n "$KEYTOOL" ] || KEYTOOL="$HOME/.jdks/temurin-17/bin/keytool"
[ -x "$KEYTOOL" ] || die "keytool not found. Set JAVA_HOME or install a JDK."

op whoami >/dev/null 2>&1 || die "Not signed in to 1Password. Run 'op signin' first."
gh auth status >/dev/null 2>&1 || die "Not authenticated to GitHub. Run 'gh auth login' first."

# Overwriting an existing key would orphan every install already out there.
[ -e "$KEYSTORE" ] && die "$KEYSTORE already exists. Refusing to overwrite a signing key."

if op item get "$ITEM" --vault "$VAULT" >/dev/null 2>&1; then
    die "1Password already has an item titled '$ITEM' in vault '$VAULT'. Refusing to create a second one."
fi

echo "Repo:     $REPO"
echo "Keystore: $KEYSTORE"
echo "1Password: '$ITEM' in vault '$VAULT'"
echo

# --- 1. password -----------------------------------------------------------
# Alphanumeric only: symbols survive fine here but have historically tripped
# quoting in Gradle/keytool toolchains, and 32 alphanumerics is ~190 bits.
echo "==> Generating password in 1Password"
op item create \
    --category=password \
    --title "$ITEM" \
    --vault "$VAULT" \
    --generate-password='letters,digits,32' \
    >/dev/null

STOREPW="$(op read "op://$VAULT/$ITEM/password")"
[ -n "$STOREPW" ] || die "Could not read the generated password back from 1Password."

# --- 2. keystore -----------------------------------------------------------
echo "==> Generating keystore"
mkdir -p "$(dirname "$KEYSTORE")"
chmod 700 "$(dirname "$KEYSTORE")"

STOREPW="$STOREPW" "$KEYTOOL" -genkeypair \
    -keystore "$KEYSTORE" \
    -alias "$ALIAS" \
    -keyalg RSA \
    -keysize 2048 \
    -validity "$VALIDITY_DAYS" \
    -dname "$DNAME" \
    -storepass:env STOREPW \
    -keypass:env STOREPW \
    >/dev/null
chmod 600 "$KEYSTORE"

# --- 3. back up the keystore itself ----------------------------------------
# The password alone is useless without this file.
echo "==> Storing keystore file in 1Password"
op document create "$KEYSTORE" \
    --title "$ITEM (keystore file)" \
    --vault "$VAULT" \
    >/dev/null

# --- 4. GitHub Actions secrets ---------------------------------------------
# Piped rather than passed as arguments, so nothing lands in ps or history.
echo "==> Setting GitHub Actions secrets"
base64 -w0 "$KEYSTORE" | gh secret set KEYSTORE_BASE64 --repo "$REPO"
printf '%s' "$STOREPW"  | gh secret set KEYSTORE_PASSWORD --repo "$REPO"
printf '%s' "$STOREPW"  | gh secret set KEY_PASSWORD --repo "$REPO"
gh secret set KEY_ALIAS --repo "$REPO" --body "$ALIAS"

# --- 5. verify -------------------------------------------------------------
echo
echo "==> Verifying"
gh secret list --repo "$REPO"
echo
echo "Certificate fingerprint (this is what must stay constant across releases):"
STOREPW="$STOREPW" "$KEYTOOL" -list -v \
    -keystore "$KEYSTORE" \
    -alias "$ALIAS" \
    -storepass:env STOREPW \
    | grep -E "SHA256:|Valid from"

cat <<EOF

Done.

  Keystore: $KEYSTORE (also in 1Password as a document)
  Password: 1Password item '$ITEM'

The next push to main will publish a release signed with this key. Anyone who
installed a previous debug-signed build must uninstall once before they can
update -- Android rejects an update whose signing certificate changed.
EOF
